components/governance/org.wso2.carbon.governance.generic/src/main/java/org/wso2/carbon/governance/generic/services/ManageGenericArtifactService.java
PR: https://wso2.org/jira/browse/REGISTRY-2381
=> Spelling mistake in log.error msg

.gitignore, components/governance/org.wso2.carbon.governance.wsdltool.ui/src/main/resources/org/wso2/carbon/governance/wsdltool/ui/i18n/JSResources.properties, components/governance/org.wso2.carbon.governance.wsdltool.ui/src/main/resources/web/resourcecompare/js/resource_visualize_util.js
https://wso2.org/jira/browse/REGISTRY-2449
=> UI Issues in Resource Compare - REGISTRY-2449 

components/governance/org.wso2.carbon.governance.wsdltool.ui/src/main/resources/org/wso2/carbon/governance/wsdltool/ui/i18n/Resources.properties, components/governance/org.wso2.carbon.governance.wsdltool.ui/src/main/resources/web/resourcecompare/regResourceCompare.jsp, components/governance/org.wso2.carbon.governance.wsdltool/src/main/java/org/wso2/carbon/governance/wsdltool/util/CommonUtil.java
https://wso2.org/jira/browse/REGISTRY-2449
=> Rectified and formatted the error msg flow - REGISTRY-2449

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/endpoints/EndpointManager.java
This is a fix for search version issues that occurred while testing.
Please merge registry PR's first related to this issue.
https://wso2.org/jira/browse/REGISTRY-2460
=> Setting the correct get method to fetch endpoint content - REGISTRY-2460

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/endpoints/dataobjects/EndpointImpl.java, components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceConstants.java, features/extensions/org.wso2.carbon.registry.extensions.server.feature/resources/rxts/endpoint.rxt
https://wso2.org/jira/browse/REGISTRY-2477
https://wso2.org/jira/browse/REGISTRY-2476
=> Workaround fix for endpoint attributes are not capturing and correcting endpoint storagePath

components/governance/org.wso2.carbon.governance.comparator/pom.xml, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/TextDiffGeneratorFactory.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/text/TextComparator.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/utils/ComparatorUtils.java
Did some changes in org.wso2.carbon.governance.comparator bundles pom file.
=> Added ComparatorUtils class and pom file changes

components/governance/org.wso2.carbon.governance.notifications.ui/src/main/java/org/wso2/carbon/governance/notifications/ui/worklist/HumanTaskClient.java
[1] https://wso2.org/jira/browse/REGISTRY-2227
=> fix for console notifications not appearing when a role has 2 or more users - REGISTRY-2227

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/common/GovernanceArtifactManager.java, components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceArtifactConfiguration.java
This PR adds mandatory field value existence checking for governance API.
=> REGISTRY-3080 - Check Mandatory Fields

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/common/GovernanceArtifactManager.java, components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceArtifactConfiguration.java
Reverts wso2/carbon-governance#126
=> Revert "REGISTRY-3080 - Check Mandatory Fields"

features/extensions/org.wso2.carbon.registry.extensions.server.feature/resources/rxts/restservice.rxt, features/extensions/org.wso2.carbon.registry.extensions.server.feature/resources/rxts/soapservice.rxt
This is an improvement which originated from the following JIRA: https://wso2.org/jira/browse/REGISTRY-3028
=> Added readonly properties to the resetservice and soapservice RXTs

components/governance/org.wso2.carbon.governance.generic.ui/src/main/resources/org/wso2/carbon/governance/generic/ui/i18n/Resources.properties, components/governance/org.wso2.carbon.governance.generic.ui/src/main/resources/web/generic/list.jsp, components/governance/org.wso2.carbon.governance.generic.ui/src/main/resources/web/generic/list_content.jsp
[1] https://wso2.org/jira/browse/REGISTRY-3377
=> REGISTRY-3377 - Removing impact analysis access links

components/governance/org.wso2.carbon.governance.lcm/src/main/java/org/wso2/carbon/governance/lcm/internal/LifeCycleServiceImpl.java
Fix for https://wso2.org/jira/browse/REGISTRY-3378
=> Add remove cache method for lifecycle state

components/governance/org.wso2.carbon.governance.api/pom.xml, components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceUtils.java, components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/TaxonomyTreeAPI.java
=> Adding taxonomy milestone-1

components/governance/org.wso2.carbon.governance.api/src/test/java/org/wso2/carbon/governance/api/test/utils/BaseTestCase.java
Reverts wso2/carbon-governance#201-downgrade the kernel version
=> Revert "fix integration test failures"

pom.xml
Reverts wso2/carbon-governance#200 -downgrade kernel version
=> Revert "Upgrade kernel version to 4.4.6-SNAPSHOT"

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/generic/dataobjects/DetachedGenericArtifactImpl.java, components/governance/org.wso2.carbon.governance.rest.api/src/main/java/org/wso2/carbon/governance/rest/api/internal/GenericArtifactMessageBodyReader.java, components/governance/org.wso2.carbon.governance.rest.api/src/main/java/org/wso2/carbon/governance/rest/api/internal/JSONMessageBodyReader.java
This PR is related to [REGISTRY-3613](https://wso2.org/jira/browse/REGISTRY-3613)
This PR enables adding multiple unbounded fields (eg: endpoints) through the Governance Rest API.
=> Fix for REGISTRY-3613

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceUtils.java
Fixed possible Null Pointer Exceptions when retrieving attributes.
=> REGISTRY-3634 : Fixing possible NPEs

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/common/dataobjects/GovernanceArtifact.java, components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/common/dataobjects/GovernanceArtifactImpl.java, components/governance/org.wso2.carbon.governance.lcm/src/main/java/org/wso2/carbon/governance/lcm/beans/LCStateBean.java, components/governance/org.wso2.carbon.governance.lcm/src/main/java/org/wso2/carbon/governance/lcm/internal/LifeCycleServiceImpl.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/aspects/DefaultLifeCycle.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/aspects/utils/LifecycleConstants.java
=> Implemented time in lifecycle feature back end to view the checkpoint time duration in publisher.

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/common/dataobjects/GovernanceArtifact.java, components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/common/dataobjects/GovernanceArtifactImpl.java, components/governance/org.wso2.carbon.governance.lcm/src/main/java/org/wso2/carbon/governance/lcm/beans/LCStateBean.java, components/governance/org.wso2.carbon.governance.lcm/src/main/java/org/wso2/carbon/governance/lcm/internal/LifeCycleServiceImpl.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/aspects/DefaultLifeCycle.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/aspects/utils/LifecycleConstants.java
Reverts wso2/carbon-governance#207
=> Revert "Implemented time in lifecycle feature back end to view the checkpoint time duration in publisher."

components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/GovernanceDiffGeneratorFactory.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/text/TextComparator.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/utils/ComparatorConstants.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/utils/ComparatorUtils.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/utils/WSDLComparisonUtils.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/wsdl/WSDLBindingsComparator.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/wsdl/WSDLComparator.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/wsdl/WSDLMessagesComparator.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/wsdl/WSDLOperationComparator.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/wsdl/WSDLPortComparator.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/wsdl/WSDLPortTypeComparator.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/wsdl/WSDLServicesComparator.java, components/governance/org.wso2.carbon.governance.comparator/src/main/java/org/wso2/carbon/governance/comparator/wsdl/WSDLTypesComparator.java
Improved some existing comparison classes and added two new comparison classes.
=> Improved back end codes to achieve section-wise comparison in G-Reg diff view

features/extensions/org.wso2.carbon.registry.extensions.server.feature/resources/rxt.xsd
=> modify xsd with taxonomies

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceUtils.java, components/governance/org.wso2.carbon.governance.taxonomy.ui/src/main/java/org/wso2/carbon/governance/taxonomy/ui/clients/TaxonomyManagementClient.java, components/governance/org.wso2.carbon.governance.taxonomy.ui/src/main/resources/web/taxonomy/delete_taxonomy-ajaxprocessor.jsp, components/governance/org.wso2.carbon.governance.taxonomy.ui/src/main/resources/web/taxonomy/save_taxonomy-ajaxprocessor.jsp, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/beans/QueryBean.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/beans/TaxonomyBean.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/IQueryProvider.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/ITaxonomyServices.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/QueryProviderImpl.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/TaxonomyManager.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/TaxonomyServicesImpl.java, features/taxonomy-management/org.wso2.carbon.governance.taxonomy.management.server.feature/pom.xml, features/taxonomy-management/org.wso2.carbon.governance.taxonomy.management.ui.feature/pom.xml, service-stubs/governance/org.wso2.carbon.governance.taxonomy.stub/src/main/resources/TaxonomyServices.wsdl
adding multiple taxonomy updates
=> REGISTRY-3666 adding multiple taxonomy updates

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceUtils.java
Fix issue with the facet query
=> Fix for REGISTRY-3690

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceUtils.java
resolve categorization query and taxonomy query fix
=> resolve categorization query and taxonomy query fix

components/governance/org.wso2.carbon.governance.taxonomy.ui/src/main/resources/META-INF/component.xml, components/governance/org.wso2.carbon.governance.taxonomy/src/main/resources/META-INF/component.xml, components/governance/org.wso2.carbon.governance.taxonomy/src/main/resources/META-INF/services.xml
REGISTRY-3806  Taxonomy Handle view permission for users
=> REGISTRY-3806  Taxonomy Handle view permission for users

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceArtifactConfiguration.java, components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceUtils.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/beans/RXTBean.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/IStorageProvider.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/ITaxonomyServices.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/QueryProviderImpl.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/StorageProviderImpl.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/TaxonomyManager.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/TaxonomyServicesImpl.java, components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/util/CommonUtils.java, features/extensions/org.wso2.carbon.registry.extensions.server.feature/resources/rxt.xsd
adding global taxonomy feature
=> adding global taxonomy feature

components/governance/org.wso2.carbon.governance.taxonomy/src/main/java/org/wso2/carbon/governance/taxonomy/services/StorageProviderImpl.java
adding initialization for taxonomy storage service getTaxonomyBeanMap
=> adding initialization for taxonomy storage service getTaxonomyBeanMap

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/generic/dataobjects/DetachedGenericArtifact.java, components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/generic/dataobjects/DetachedGenericArtifactImpl.java, components/governance/org.wso2.carbon.governance.rest.api/src/main/java/org/wso2/carbon/governance/rest/api/Asset.java
Reverts wso2/carbon-governance#260
=> Revert "Fix update issue in Governance REST API PUT method"

components/governance/org.wso2.carbon.governance.generic.ui/src/main/resources/web/generic/source_artifact.jsp
Resolve #SECURITYINTERNAL-179 - Fixed identified cross site scripting vulnerabilities
=> SECURITYINTERNAL-179 - Fix cross site scripting vulnerabilities

components/governance/org.wso2.carbon.governance.generic.ui/src/main/resources/web/generic/source_artifact.jsp
Apply proper encoding where appropriate
=> Apply proper output encoding

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceUtils.java
Jira: https://wso2.org/jira/browse/REGISTRY-3932
=> Fix for governanceArtifactConfigurations list being empty

components/governance/org.wso2.carbon.governance.registry.eventing/src/main/java/org/wso2/carbon/governance/registry/eventing/handlers/GovernanceEventingHandler.java
=> Fix multiple notification for lc checklist

components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/utils/CommonUtil.java
https://wso2.org/jira/browse/REGISTRY-3900
=> REGISTRY-3900: Keep configured order of association types

components/governance/org.wso2.carbon.governance.lcm.ui/src/main/java/org/wso2/carbon/governance/lcm/ui/clients/LifeCycleManagementServiceClient.java, components/governance/org.wso2.carbon.governance.lcm/src/main/java/org/wso2/carbon/governance/lcm/util/CommonUtil.java
=> Fix lifecycle configuration page loading issue

components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/utils/CommonUtil.java
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Improve xml parsing logic

components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/indexers/RXTIndexer.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/utils/CommonUtil.java
Fix the indexing issue in unbounded rxt fields
Resolves: #254
=> Fix unbounded fields searching issue

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceUtils.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/executors/APIPublishExecutor.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/executors/utils/Utils.java
This PR includes a revision suggested in a PR review
=> Improvements suggested by reviews

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/generic/GenericArtifactManager.java
Added context information for exception handling.
=> Removed error log replication.

components/governance/org.wso2.carbon.governance.rest.api/src/main/java/org/wso2/carbon/governance/rest/api/internal/GenericArtifactJSONWriter.java, components/governance/org.wso2.carbon.governance.rest.api/src/main/java/org/wso2/carbon/governance/rest/api/internal/JSONMessageBodyReader.java
in the default G-Reg pack, unable to add and retrieve asset information with multivalue attributes using Governance REST API.
Example Post Body:
```
`{
"name":"SimpleRestService",
"type":"restservice",
"context":"/test1",
"version":"1.0.0",
"uritemplate_urlPattern": ["/sample","/test","/help","/saneth"],
"uritemplate_httpVerb": ["get","get","post","put"]
}`
```
Example Get Response:
```
`
{
"assets": [
{
"name": "FirstRestService",
"id": "ab5acc3a-830e-4621-b5c0-319967d169b4",
"type": "restservice",
"uritemplate_urlPattern": [
"/sample",
"/test",
"/help",
"/saneth"
],
"uritemplate_authType": [
" ",
" ",
" ",
" "
],
"context": "/test1",
"endpoints": null,
"version": "1.0.0",
"security_authenticationType": "None",
"contacts_entry": [
{
"Contact Type": "Technical Owner",
"Contact …
```
=> Fixes to add and retrieve unbounded table via governance rest API

components/governance/org.wso2.carbon.governance.taxonomy.ui/src/main/resources/web/taxonomy/docs/userguide.html
Resolves wso2/product-greg#882
Avoid build fail
Fixing userguide.xml formatting issue and bumping product 
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
Any
=> Fix userguide formatting issue.

components/governance/org.wso2.carbon.governance.rest.api/src/main/java/org/wso2/carbon/governance/rest/api/internal/GenericArtifactJSONWriter.java
Fixes for Governance REST API GET response json has two type parameters
> Link(s) to product documentation that addresses the …
=> Fixes for Governance REST API GET response json has two type parameters

components/governance/org.wso2.carbon.governance.lcm.ui/src/main/resources/web/lcm/source_lcm.jsp
This PR adds HTMLAttribute encoding for lifecycleName request parameter value.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training …
=> Add HTMLAttribute encoding for lifecycleName request parameter value

components/governance/org.wso2.carbon.governance.rest.api/src/main/java/org/wso2/carbon/governance/rest/api/security/AuthenticationHandler.java
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Fix for https://github.com/wso2/product-greg/issues/889.

pom.xml
=> Upgrade Solr version to 5.5.5

components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/executors/APIDeleteExecutor.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/executors/APIPublishExecutor.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/executors/apistore/APIDeleteExecutor.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/executors/apistore/ApiStore2Executor.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/executors/apistore/ApiStoreExecutor.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/executors/apistore/RestServiceToAPIExecutor.java, pom.xml
- Change the org.wso2.securevault version to 1.1.2
- Resolve the secrets usingMiscellaneousUtil.resolve() method.
=> Add secure vault changes.

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceUtils.java, components/governance/org.wso2.carbon.governance.registry.extensions/src/org/wso2/carbon/governance/registry/extensions/internal/GovernanceRegistryExtensionsComponent.java
fixing https://github.com/wso2/product-apim/issues/5223
=> Add rxt to registry (to UnboundedFieldMap) during startup for super tenant and add overview_ only for relavant fiel queries

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceUtils.java
fixing https://github.com/wso2/product-apim/issues/5223
=> set isMultiValueField as public static and implement the method inside governanceutil

components/governance/org.wso2.carbon.governance.client/src/main/java/org/wso2/carbon/governance/client/internal/WSRegistrySearchComponent.java, pom.xml
=> change service component name

components/governance/org.wso2.carbon.governance.api/pom.xml, components/governance/org.wso2.carbon.governance.comparator/pom.xml, components/governance/org.wso2.carbon.governance.custom.lifecycles.checklist/pom.xml, components/governance/org.wso2.carbon.governance.gadgets/org.wso2.carbon.governance.gadgets.impactanalysis/pom.xml, components/governance/org.wso2.carbon.governance.gadgets/org.wso2.carbon.governance.gadgets.resourceimpact/pom.xml, components/governance/org.wso2.carbon.governance.gadgetsource/pom.xml, components/governance/org.wso2.carbon.governance.generic.ui/pom.xml, components/governance/org.wso2.carbon.governance.lcm/pom.xml, components/governance/org.wso2.carbon.governance.list.ui/pom.xml, components/governance/org.wso2.carbon.governance.metadata/pom.xml, components/governance/org.wso2.carbon.governance.registry.eventing/pom.xml, components/governance/org.wso2.carbon.governance.registry.extensions/pom.xml, components/governance/org.wso2.carbon.governance.sramp/pom.xml, components/governance/org.wso2.carbon.governance.taxonomy/pom.xml, components/governance/org.wso2.carbon.governance.wsdltool/pom.xml, components/ws-discovery-proxy/org.wso2.carbon.discovery.proxy/pom.xml, features/governance-gadgets/org.wso2.carbon.governance.gadgets.ui.feature/pom.xml, pom.xml
Update carbon.registry.version
update kernel.feature.version
=> Update multiple versions

pom.xml
=> Update registry version

pom.xml
> This PR will update dependency versions regarding the kernel upgrade
=> Update dependency versions regarding the kernel upgrade

components/governance/org.wso2.carbon.governance.common/src/main/java/org/wso2/carbon/governance/common/utils/GovernanceUtils.java
> Fix improper restriction of XXE
=> Fix improper restriction of XXE

components/governance/org.wso2.carbon.governance.generic.ui/src/main/java/org/wso2/carbon/governance/generic/ui/utils/GenericUtil.java, components/governance/org.wso2.carbon.governance.generic/src/main/java/org/wso2/carbon/governance/generic/util/GenericArtifactUtil.java, components/governance/org.wso2.carbon.governance.generic/src/main/java/org/wso2/carbon/governance/generic/util/Util.java
=> Added secured document builder.

components/governance/org.wso2.carbon.governance.generic.ui/src/main/resources/web/generic/delete_ajaxprocessor.jsp, components/governance/org.wso2.carbon.governance.generic.ui/src/main/resources/web/generic/save_artifact_ajaxprocessor.jsp
The following ajaxprocessors will be authenticated when request is made. 
- delete_ajaxprocessor.jsp
- save_artifact_ajaxprocessor.jsp
Check authentication when the request is made and if the request is unauthenticated it will be redirected to login page.
=> Adding authentication mechanism to ajaxProcessors

components/governance/org.wso2.carbon.governance.generic/src/main/java/org/wso2/carbon/governance/generic/util/Util.java
Fix review comments of https://github.com/wso2-support/carbon-governance/pull/95
=> Removed error log and added description.

components/governance/org.wso2.carbon.governance.generic.ui/src/main/resources/web/generic/list.jsp
This PR adds javascript encoding for delete artifact function parameter.
=> Add Javascript encoding for delete artifact

components/governance/org.wso2.carbon.governance.api/src/main/java/resources/policy/EncrOnlyAnonymous.xml, components/governance/org.wso2.carbon.governance.api/src/main/java/resources/policy/SgnEncrAnonymous.xml, components/governance/org.wso2.carbon.governance.api/src/main/java/resources/policy/SigEncr.xml, components/governance/org.wso2.carbon.governance.api/src/main/java/resources/policy/policy.xml, components/governance/org.wso2.carbon.governance.api/src/main/java/resources/purchasing.xsd, components/governance/org.wso2.carbon.governance.api/src/main/java/resources/wsdl/BizService.wsdl, components/governance/org.wso2.carbon.governance.api/src/main/java/resources/wsdl/MyChangedBizService.wsdl, components/governance/org.wso2.carbon.governance.api/src/main/java/resources/xsd/purchasing.xsd, components/governance/org.wso2.carbon.governance.api/src/main/java/resources/xsd/purchasing_dup.xsd
=> Adding unit test resources

components/governance/org.wso2.carbon.governance.generic.ui/src/main/resources/web/generic/basic_filter_ajaxprocessor.jsp, components/governance/org.wso2.carbon.governance.generic.ui/src/main/resources/web/generic/filter_lc_ajaxprocessor.jsp, components/governance/org.wso2.carbon.governance.generic.ui/src/main/resources/web/generic/list.jsp
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Fix encoding issues

components/governance/org.wso2.carbon.governance.api/src/main/java/org/wso2/carbon/governance/api/util/GovernanceUtils.java
> To support the fix for https://github.com/wso2/product-apim/issues/4869
=> add result grouping support

pom.xml
update carbon.registry.version to 4.7.46
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> update carbon.registry.version to 4.7.46

pom.xml
=> Updating registry version

components/governance/org.wso2.carbon.governance.api/pom.xml, pom.xml
=> Fix build failure on JDK 11

components/governance/org.wso2.carbon.governance.generic/src/main/resources/META-INF/services.xml
This PR updates the `ManageGenericArtifactService` permissions to be more restrictive.
=> Update ManageGenericArtifactService permissions to be more restrictive
